#!/bin/bash

# ============================================
# Ambitopia [yellow]
# ============================================

options=(
	style=round
	width=4.0
	hidpi=on
	active_color=0xfffdf400
	inactive_color=0x00000000
    blacklist="Finder,System Settings"
)
borders "${options[@]}"